test_requirements: do not pin selenium to 2.37.2
I was seeing the following error with selenium tests, which is fixed in
a later version:

> WebDriverException: Message: "Can't load the profile. Profile Dir: …"