Use master.tar.gz instead of master.zip
To avoid:

Collecting https://github.com/django/django/archive/master.zip
  Downloading https://github.com/django/django/archive/master.zip
  Exception:
  Traceback (most recent call last):
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/req/req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/download.py", line 782, in unpack_url
      session,
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/download.py", line 671, in unpack_http_url
      unpack_file(from_path, location, content_type, link)
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/utils/__init__.py", line 648, in unpack_file
      flatten=not filename.endswith('.whl')
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/utils/__init__.py", line 528, in unzip_file
      leading = has_leading_dir(zip.namelist()) and flatten
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/utils/__init__.py", line 253, in has_leading_dir
      prefix, rest = split_leading_dir(path)
    File "/home/travis/build/yourlabs/django-autocomplete-light/.tox/py27-djangomaster/lib/python2.7/site-packages/pip/utils/__init__.py", line 237, in split_leading_dir
      path = str(path)
  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2297' in position 60: ordinal not in range(128)