tox.ini: add DISPLAY to passenv
This is required to fix the following error with `tox -e py34-django18`
(using Firefox):

> selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect.