Test on chromium
Selenium and Firefox have started to fail with error::

    WebDriverException: Message: 'geckodriver' executable needs to be in PATH.